test_entries = [
    {
        "series": "TC America",
        "event": "Sonoma Raceway",
        "class": "TCA",
        "number": "9",
        "team": "Skip Barber Racing",
        "driver1firstName": "Matt",
        "driver1lastName": "Chapman",
        "driver1nationality": "USA",
        "car": "Honda Civic Si",
        "manufacturer": "Honda",
        "sponsors": "Mustaches, BioSteel"
    },
    {
        "series": "TC America",
        "event": "FULL SEASON ENTRY",
        "class": "TC",
        "number": "56",
        "team": "Blue Jays Racing",
        "driver1firstName": "Roy",
        "driver1lastName": "Halladay",
        "driver1nationality": "USA",
        "car": "Honda Civic Type-R TC",
        "manufacturer": "Honda",
        "sponsors": ""
    },
    {
        "series": "TC America",
        "event": "Sonoma Raceway",
        "class": "TC",
        "number": " 50",
        "team": "Bo Racing",
        "driver1firstName": "Bo",
        "driver1lastName": "Bichette",
        "driver1nationality": "USA",
        "car": "Mazda 3",
        "manufacturer": "Mazda",
        "sponsors": ""
    },
    {
        "series": "TC America",
        "event": "Sonoma Raceway",
        "class": "TCX",
        "number": "80",
        "team": "VG Racing",
        "driver1firstName": "Vladamir",
        "driver1lastName": "Guerrero",
        "driver1nationality": "USA",
        "car": "Acura Integra",
        "manufacturer": "Acura",
        "sponsors": "Mary Browns Chicken"
    },
    {
        "series": "GT4 America",
        "event": "Sonoma Raceway",
        "class": "Silver",
        "number": "28",
        "team": "G Speed",
        "driver1firstName": "Kevin",
        "driver1lastName": "Gausman",
        "driver1category": "Silver",
        "driver1nationality": "USA",
        "driver2firstName": "Chris",
        "driver2lastName": "Bassatt",
        "driver2category": "Silver",
        "driver2nationality": "CAN",
        "car": "Porsche 718 Cayman CS",
        "manufacturer": "Porsche",
        "sponsors": "Cy Young"
    },
    {
        "series": "GT4 America",
        "event": "Sonoma Raceway",
        "class": "Am",
        "number": "888",
        "team": "Audi Sport Team Asia",
        "driver1firstName": "Yusei",
        "driver1lastName": "Kikuchi",
        "driver1category": "Bronze",
        "driver1nationality": "JAP",
        "driver2firstName": "Hyun Jin",
        "driver2lastName": "Ryu",
        "driver2category": "Bronze",
        "driver2nationality": "KOR",
        "car": "Audi R8 LMS GT4",
        "manufacturer": "Audi",
        "sponsors": "Rice"
    },
    {
        "series": "GT America",
        "event": "Sonoma Raceway",
        "class": "GT4",
        "number": "2",
        "team": "Big Motorsports",
        "driver1firstName": "Cavan",
        "driver1lastName": "Biggio",
        "driver1nationality": "USA",
        "car": "Mercedes-AMG GT4",
        "manufacturer": "Mercedes",
        "sponsors": "Craig Biggio"
    },
    {
        "series": "GT America",
        "event": "Sonoma Raceway",
        "class": "SRO3",
        "number": "333",
        "team": "Schnieder Racing",
        "driver1firstName": "John",
        "driver1lastName": "Schnieder",
        "driver1nationality": "USA",
        "car": "Audi R8 LMS GT3 Evo 2",
        "manufacturer": "Audi",
        "sponsors": "Schneider Hot Dogs"
    },
    {
        "series": "GT America",
        "event": "Sonoma Raceway",
        "class": "GT2",
        "number": "222",
        "team": "Varsho Autosport",
        "driver1firstName": "Dalton",
        "driver1lastName": "Varsho",
        "driver1nationality": "USA",
        "car": "KTM X-Bow GT2",
        "manufacturer": "KTM",
        "sponsors": ""
    },
    {
        "series": "GT World Challenge America",
        "event": "Sonoma Raceway",
        "class": "Pro-Am",
        "number": "6",
        "team": "K-Pax Racing",
        "driver1firstName": "Kevin",
        "driver1lastName": "Kiermier",
        "driver1category": "Platinum",
        "driver1nationality": "USA",
        "driver2firstName": "George",
        "driver2lastName": "Springer",
        "driver2category": "Bronze",
        "driver2nationality": "USA",
        "car": "Lamborghini Huarcan GT3 EVO",
        "manufacturer": "Lamborghini",
        "sponsors": ""
    },
    {
        "series": "GT World Challenge America",
        "event": "Sonoma Raceway",
        "class": "Am",
        "number": "55",
        "team": "Turner Motorsports",
        "driver1firstName": "Jose",
        "driver1lastName": "Bautista",
        "driver1category": "Bronze",
        "driver1nationality": "USA",
        "driver2firstName": "Russell",
        "driver2lastName": "Martin",
        "driver2category": "Bronze",
        "driver2nationality": "USA",
        "car": "Porsche 992 GT3 R",
        "manufacturer": "Porsche",
        "sponsors": ""
    },

]
