vehicles = {
    'acuraNsxGt3Evo22': 'Acura NSX GT3 EVO22',
    'astonMartinVantageAmrGt3': 'Aston Martin Vantage AMR GT3',
    'audiR8LmsGt2': 'Audi R8 LMS GT2',
    'bmwM4Gt3': 'BMW M4 GT3',
    'chevroletCorvetteZ06Gt3.r': 'Chevrolet Corvette Z06 GT3.R',
    'ferrari296Gt3': 'Ferrari 296 GT3',
    'fordMustangGt3': 'Ford Mustang GT3',
    'mercedes-amgGt3': 'Mercedes-AMG GT3',
    'ktmX-bowGt2': 'KTM X-Bow GT2',
    'nissanZGt4': 'Nissan Z GT4',
    'bmwM4Gt4': 'BMW M4 GT4',
    'fordMustangGt4': 'Ford Mustang GT4',
    'mclarenArturaGt4': 'McLaren Artura GT4',
    'mercedes-amgGt4': 'Mercedes-AMG GT4',
    'porsche718CaymanGt4RsClubsport': 'Porsche 718 Cayman GT4 RS Clubsport',
    'toyotaGazooRacingGrSupraGt4Evo': 'Toyota Gazoo Racing GR Supra GT4 EVO',
    'toyotaGazooRacingGr': "Toyota Gazoo Racing GR Supra GT4 EVO",
    'acuraIntegraTypeS': 'Acura Integra Type S TCX',
    'subaruBrz': 'Subaru BRZ',
    'audiR8LmsGt4': 'Audi R8 LMS GT4',
    'audiR8Lms': 'Audi R8 LMS',
    'callawayCorvetteZ066rGt3': 'Callaway Corvette Z06R GT3',
    'astonMartinVantageAmrr': 'Aston Martin Vantage AMR GT4',
    'mercedesamgGt3': 'Mercedes-AMG GT3',
    'bmwM4Gt42': 'BMW M4 GT4',
    'porsche718CaymanGt42': "Porsche 718 Cayman GT4 RS CS",
    'astonMartinVantageAmr': "Aston Martin Vantage AMR GT3",
    'porsche911Gt3R3': "Porsche 992 GT3 R",
    "mercedesamgGt2": "Mercedes-AMG GT2",
    "hondaCivicSiFe1": "Honda Civic Si FE1",
    "bmwM2Cs": "BMW M2 CS (Cup)",
    "hyundaiElantraNCup": "Hyundai Elantra N Cup",
    "hondaCivicTyper": "Honda Civic Type R",
    "miniCooperJcw": "MINI JCW",
    "mazda3Tc": "Mazda 3",
    "miniJcwProTc": "MINI JCW TC Pro",
    "astonMarinVantageAmr": "Aston Martin Vantage AMR GT3",
    "audiR8LmsGt3": "Audi R8 LMS GT3",
    "porsche911Gt3R2": "Porsche 992 GT3 R",
    "lamborghiniHuracanSuperTrofeo2": "Lamborghini Huracan Super Trofeo EVO2",
    "porsche718CaymanGt4": "Porsche 718 Cayman GT4 RS Clubsport",
    "mercedesamgGt4": "Mercedes-AMG GT4",
}
